project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"

website:
  title: "Reproducible research"
  page-footer: "This page was built with ❤️, [R](https://cran.r-project.org) and [Quarto](https://quarto.org/) by REVELO"
  navbar:
    background: "#447099"
    logo: "materials/images/revelo.png"
    search: true
    left:
      - href: index.qmd
        text: "Home"
      - materials/about.qmd
      - text: "Lezioni"
        menu: 
          - href: materials/intro.qmd
            text: "Modulo I: Introduzione al corso"
          - href: https://phd-toolbox-course.github.io/2022_PhD_Toolbox_course/M4_RicercaRiproducibile.html#1
            text: "Modulo II: Ricerca riproducibile"
          - href: materials/qi.qmd
            text: "Modulo III: Introduzione a Quarto"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



